In [1]:
# ============================================================
# SEMANTIC THRESHOLD tau SENSITIVITY ANALYSIS
# ============================================================

import time
import itertools
import pandas as pd
import networkx as nx
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# tau values to compare
TAU_VALUES = [0.30, 0.40, 0.50, 0.60]

# Evaluate the final backbone used in the paper
W_BACKBONE = 20

# ============================================================
# 1) NORMALIZE KEYWORDS ONCE
# ============================================================

docs_keywords = []

for kws in df["keywords_llm"].tolist():
    kws_clean = [
        k.strip().lower()
        for k in kws
        if isinstance(k, str) and k.strip()
    ]
    kws_clean = sorted(set(kws_clean))
    if len(kws_clean) > 0:
        docs_keywords.append(kws_clean)

print(f"Documents with valid keywords: {len(docs_keywords):,}")

# ============================================================
# 2) CREATE UNIQUE VOCABULARY AND EMBEDDINGS ONCE
# ============================================================

vocab = sorted(set(k for kws in docs_keywords for k in kws))

print(f"Unique vocabulary: {len(vocab):,}")

print("Computing global keyword embeddings...")
emb_matrix = model.encode(
    vocab,
    normalize_embeddings=True,
    show_progress_bar=True
)

embeddings_dict = {
    kw: emb_matrix[i]
    for i, kw in enumerate(vocab)
}

print("Embeddings ready.")

# ============================================================
# 3) FUNCTION TO BUILD THE CRS FOR A GIVEN tau
# ============================================================

def build_crs_for_tau(docs_keywords, embeddings_dict, tau):
    G = nx.Graph()

    for idx, kws in enumerate(docs_keywords, start=1):

        # Add nodes and document frequency
        for k in kws:
            if G.has_node(k):
                G.nodes[k]["doc_freq"] += 1
            else:
                G.add_node(k, doc_freq=1)

        if len(kws) < 2:
            continue

        # Local embedding matrix
        local_emb = np.array([embeddings_dict[k] for k in kws])
        S = cosine_similarity(local_emb)

        # Local edges filtered by tau
        for i, j in itertools.combinations(range(len(kws)), 2):
            sim = float(S[i, j])

            if sim >= tau:
                a, b = kws[i], kws[j]

                if G.has_edge(a, b):
                    G[a][b]["weight"] += 1
                    G[a][b]["sim_sum"] += sim
                    G[a][b]["sim_count"] += 1
                else:
                    G.add_edge(
                        a,
                        b,
                        weight=1,
                        sim_sum=sim,
                        sim_count=1
                    )

    # Mean similarity
    for u, v, d in G.edges(data=True):
        d["sim_mean"] = d["sim_sum"] / d["sim_count"]

    return G

# ============================================================
# 4) FUNCTION TO COMPUTE METRICS
# ============================================================

def graph_metrics(G, tau, w_backbone=20):
    n = G.number_of_nodes()
    e = G.number_of_edges()
    density = nx.density(G) if n > 1 else 0

    components = nx.number_connected_components(G) if n > 0 else 0

    if n > 0 and e > 0:
        lcc_nodes = max(nx.connected_components(G), key=len)
        L = G.subgraph(lcc_nodes).copy()
        lcc_nodes_n = L.number_of_nodes()
        lcc_edges_n = L.number_of_edges()
        lcc_ratio = lcc_nodes_n / n
    else:
        lcc_nodes_n = 0
        lcc_edges_n = 0
        lcc_ratio = 0

    # Backbone w >= 20
    H = nx.Graph()
    H.add_nodes_from(G.nodes(data=True))
    H.add_edges_from([
        (u, v, d)
        for u, v, d in G.edges(data=True)
        if float(d.get("weight", 1)) >= w_backbone
    ])
    H.remove_nodes_from([node for node in list(H.nodes()) if H.degree(node) == 0])

    hn = H.number_of_nodes()
    he = H.number_of_edges()
    h_density = nx.density(H) if hn > 1 else 0
    h_components = nx.number_connected_components(H) if hn > 0 else 0

    if hn > 0 and he > 0:
        h_lcc_nodes = max(nx.connected_components(H), key=len)
        HL = H.subgraph(h_lcc_nodes).copy()
        h_lcc_n = HL.number_of_nodes()
        h_lcc_e = HL.number_of_edges()
        h_lcc_ratio = h_lcc_n / hn
    else:
        h_lcc_n = 0
        h_lcc_e = 0
        h_lcc_ratio = 0

    # Louvain modularity in the backbone
    try:
        import community as community_louvain
        if hn > 0 and he > 0:
            part = community_louvain.best_partition(
                H,
                weight="weight",
                random_state=42
            )
            modularity = community_louvain.modularity(
                part,
                H,
                weight="weight"
            )
            n_communities = len(set(part.values()))
        else:
            modularity = np.nan
            n_communities = 0
    except Exception:
        modularity = np.nan
        n_communities = np.nan

    return {
        "tau": tau,
        "nodes_global": n,
        "edges_global": e,
        "density_global": density,
        "components_global": components,
        "lcc_nodes_global": lcc_nodes_n,
        "lcc_edges_global": lcc_edges_n,
        "lcc_ratio_global": lcc_ratio,
        "nodes_backbone_w20": hn,
        "edges_backbone_w20": he,
        "density_backbone_w20": h_density,
        "components_backbone_w20": h_components,
        "lcc_nodes_backbone_w20": h_lcc_n,
        "lcc_edges_backbone_w20": h_lcc_e,
        "lcc_ratio_backbone_w20": h_lcc_ratio,
        "modularity_backbone_w20": modularity,
        "communities_backbone_w20": n_communities
    }

# ============================================================
# 5) RUN SENSITIVITY ANALYSIS
# ============================================================

sensitivity_results = []

for tau in TAU_VALUES:
    print("\n" + "="*60)
    print(f"Building CRS for tau = {tau}")
    print("="*60)

    start = time.time()

    G_tau = build_crs_for_tau(
        docs_keywords=docs_keywords,
        embeddings_dict=embeddings_dict,
        tau=tau
    )

    metrics = graph_metrics(
        G=G_tau,
        tau=tau,
        w_backbone=W_BACKBONE
    )

    elapsed = time.time() - start
    metrics["runtime_seconds"] = elapsed

    sensitivity_results.append(metrics)

    print(f"tau = {tau}")
    print(f"Global |V| = {metrics['nodes_global']:,}")
    print(f"Global |E| = {metrics['edges_global']:,}")
    print(f"Global density = {metrics['density_global']:.6f}")
    print(f"Global LCC ratio = {metrics['lcc_ratio_global']:.4f}")
    print(f"Backbone w >= {W_BACKBONE} |V| = {metrics['nodes_backbone_w20']:,}")
    print(f"Backbone w >= {W_BACKBONE} |E| = {metrics['edges_backbone_w20']:,}")
    print(f"Backbone LCC ratio = {metrics['lcc_ratio_backbone_w20']:.4f}")
    print(f"Backbone modularity = {metrics['modularity_backbone_w20']}")
    print(f"Time = {elapsed/60:.2f} minutes")

# ============================================================
# 6) FINAL TABLE
# ============================================================

df_tau_sensitivity = pd.DataFrame(sensitivity_results)

pd.set_option("display.max_columns", None)
display(df_tau_sensitivity)

# Save results
OUT_TAU = "outputs/tau_sensitivity.csv"
df_tau_sensitivity.to_csv(OUT_TAU, index=False)

print(f"\nResults saved to:")
print(OUT_TAU)

# ============================================================
# 7) SUMMARY TABLE FOR THE PAPER
# ============================================================

summary_cols = [
    "tau",
    "nodes_global",
    "edges_global",
    "density_global",
    "lcc_ratio_global",
    "nodes_backbone_w20",
    "edges_backbone_w20",
    "lcc_ratio_backbone_w20",
    "modularity_backbone_w20",
    "communities_backbone_w20"
]

df_tau_summary = df_tau_sensitivity[summary_cols].copy()

display(df_tau_summary)

OUT_TAU_SUMMARY = "outputs/tau_sensitivity_summary.csv"
df_tau_summary.to_csv(OUT_TAU_SUMMARY, index=False)

print(f"\nSummary table saved to:")
print(OUT_TAU_SUMMARY)

Documents with valid keywords: 52,946
Unique vocabulary: 56,635
Computing global keyword embeddings...

Batches:   0%|          | 0/1770 [00:00<?, ?it/s]

Batches:   0%|          | 2/1770 [00:00<02:29, 11.86it/s]

Batches:   0%|          | 4/1770 [00:00<01:57, 15.01it/s]

Batches:   0%|          | 6/1770 [00:00<01:50, 15.98it/s]

Batches:   0%|          | 8/1770 [00:00<01:43, 16.96it/s]

Batches:   1%|          | 10/1770 [00:00<01:38, 17.86it/s]

Batches:   1%|          | 12/1770 [00:00<01:36, 18.16it/s]

Batches:   1%|          | 15/1770 [00:00<01:35, 18.32it/s]

Batches:   1%|          | 17/1770 [00:00<01:35, 18.28it/s]

Batches:   1%|          | 19/1770 [00:01<01:33, 18.72it/s]

Batches:   1%|          | 21/1770 [00:01<01:32, 18.98it/s]

Batches:   1%|▏         | 23/1770 [00:01<01:35, 18.31it/s]

Batches:   1%|▏         | 25/1770 [00:01<01:33, 18.58it/s]

Batches:   2%|▏         | 28/1770 [00:01<01:27, 19.91it/s]

Batches:   2%|▏         | 30/1770 [00:01<01:28, 19.58it/s]

Batches:   2%|▏         | 32/1770 [00:01<01:28, 19.60it/s]

Batches:   2%|▏         | 35/1770 [00:01<01:25, 20.33it/s]

Batches:   2%|▏         | 38/1770 [00:02<01:24, 20.43it/s]

Batches:   2%|▏         | 41/1770 [00:02<01:23, 20.71it/s]

Batches:   2%|▏         | 44/1770 [00:02<01:23, 20.60it/s]

Batches:   3%|▎         | 47/1770 [00:02<01:24, 20.41it/s]

Batches:   3%|▎         | 50/1770 [00:02<01:21, 21.18it/s]

Batches:   3%|▎         | 53/1770 [00:02<01:17, 22.23it/s]

Batches:   3%|▎         | 56/1770 [00:02<01:15, 22.85it/s]

Batches:   3%|▎         | 59/1770 [00:02<01:15, 22.53it/s]

Batches:   4%|▎         | 62/1770 [00:03<01:17, 22.01it/s]

Batches:   4%|▎         | 65/1770 [00:03<01:19, 21.35it/s]

Batches:   4%|▍         | 68/1770 [00:03<01:25, 19.83it/s]

Batches:   4%|▍         | 71/1770 [00:03<01:29, 18.97it/s]

Batches:   4%|▍         | 73/1770 [00:03<01:29, 19.03it/s]

Batches:   4%|▍         | 75/1770 [00:03<01:32, 18.36it/s]

Batches:   4%|▍         | 78/1770 [00:03<01:26, 19.63it/s]

Batches:   5%|▍         | 81/1770 [00:04<01:21, 20.78it/s]

Batches:   5%|▍         | 84/1770 [00:04<01:17, 21.85it/s]

Batches:   5%|▍         | 87/1770 [00:04<01:14, 22.54it/s]

Batches:   5%|▌         | 90/1770 [00:04<01:14, 22.43it/s]

Batches:   5%|▌         | 93/1770 [00:04<01:13, 22.87it/s]

Batches:   5%|▌         | 96/1770 [00:04<01:12, 23.07it/s]

Batches:   6%|▌         | 99/1770 [00:04<01:11, 23.22it/s]

Batches:   6%|▌         | 102/1770 [00:04<01:12, 23.09it/s]

Batches:   6%|▌         | 105/1770 [00:05<01:10, 23.46it/s]

Batches:   6%|▌         | 108/1770 [00:05<01:11, 23.17it/s]

Batches:   6%|▋         | 111/1770 [00:05<01:10, 23.55it/s]

Batches:   6%|▋         | 114/1770 [00:05<01:11, 23.04it/s]

Batches:   7%|▋         | 117/1770 [00:05<01:12, 22.86it/s]

Batches:   7%|▋         | 120/1770 [00:05<01:13, 22.52it/s]

Batches:   7%|▋         | 123/1770 [00:05<01:11, 22.88it/s]

Batches:   7%|▋         | 126/1770 [00:06<01:12, 22.53it/s]

Batches:   7%|▋         | 129/1770 [00:06<01:20, 20.48it/s]

Batches:   7%|▋         | 132/1770 [00:06<01:24, 19.38it/s]

Batches:   8%|▊         | 134/1770 [00:06<01:32, 17.72it/s]

Batches:   8%|▊         | 136/1770 [00:06<01:35, 17.08it/s]

Batches:   8%|▊         | 138/1770 [00:06<01:32, 17.61it/s]

Batches:   8%|▊         | 141/1770 [00:06<01:21, 20.03it/s]

Batches:   8%|▊         | 144/1770 [00:07<01:15, 21.42it/s]

Batches:   8%|▊         | 147/1770 [00:07<01:14, 21.77it/s]

Batches:   8%|▊         | 150/1770 [00:07<01:13, 22.07it/s]

Batches:   9%|▊         | 153/1770 [00:07<01:13, 22.06it/s]

Batches:   9%|▉         | 156/1770 [00:07<01:10, 22.85it/s]

Batches:   9%|▉         | 159/1770 [00:07<01:09, 23.28it/s]

Batches:   9%|▉         | 162/1770 [00:07<01:08, 23.51it/s]

Batches:   9%|▉         | 165/1770 [00:07<01:08, 23.33it/s]

Batches:   9%|▉         | 168/1770 [00:08<01:07, 23.86it/s]

Batches:  10%|▉         | 171/1770 [00:08<01:06, 23.91it/s]

Batches:  10%|▉         | 174/1770 [00:08<01:04, 24.73it/s]

Batches:  10%|█         | 177/1770 [00:08<01:04, 24.56it/s]

Batches:  10%|█         | 180/1770 [00:08<01:04, 24.69it/s]

Batches:  10%|█         | 183/1770 [00:08<01:05, 24.39it/s]

Batches:  11%|█         | 186/1770 [00:08<01:03, 24.92it/s]

Batches:  11%|█         | 189/1770 [00:08<01:04, 24.66it/s]

Batches:  11%|█         | 192/1770 [00:08<01:02, 25.30it/s]

Batches:  11%|█         | 195/1770 [00:09<01:04, 24.26it/s]

Batches:  11%|█         | 198/1770 [00:09<01:06, 23.73it/s]

Batches:  11%|█▏        | 201/1770 [00:09<01:05, 23.81it/s]

Batches:  12%|█▏        | 204/1770 [00:09<01:10, 22.33it/s]

Batches:  12%|█▏        | 207/1770 [00:09<01:09, 22.35it/s]

Batches:  12%|█▏        | 210/1770 [00:09<01:18, 19.97it/s]

Batches:  12%|█▏        | 213/1770 [00:10<01:19, 19.67it/s]

Batches:  12%|█▏        | 216/1770 [00:10<01:19, 19.50it/s]

Batches:  12%|█▏        | 219/1770 [00:10<01:15, 20.64it/s]

Batches:  13%|█▎        | 222/1770 [00:10<01:10, 22.10it/s]

Batches:  13%|█▎        | 225/1770 [00:10<01:07, 22.88it/s]

Batches:  13%|█▎        | 228/1770 [00:10<01:04, 23.84it/s]

Batches:  13%|█▎        | 231/1770 [00:10<01:03, 24.20it/s]

Batches:  13%|█▎        | 234/1770 [00:10<01:02, 24.58it/s]

Batches:  13%|█▎        | 237/1770 [00:11<01:01, 24.86it/s]

Batches:  14%|█▎        | 240/1770 [00:11<01:00, 25.45it/s]

Batches:  14%|█▎        | 243/1770 [00:11<01:00, 25.31it/s]

Batches:  14%|█▍        | 246/1770 [00:11<01:01, 24.61it/s]

Batches:  14%|█▍        | 249/1770 [00:11<01:03, 23.94it/s]

Batches:  14%|█▍        | 252/1770 [00:11<01:04, 23.63it/s]

Batches:  14%|█▍        | 255/1770 [00:11<01:07, 22.43it/s]

Batches:  15%|█▍        | 258/1770 [00:11<01:12, 20.81it/s]

Batches:  15%|█▍        | 261/1770 [00:12<01:16, 19.75it/s]

Batches:  15%|█▍        | 264/1770 [00:12<01:14, 20.23it/s]

Batches:  15%|█▌        | 267/1770 [00:12<01:12, 20.63it/s]

Batches:  15%|█▌        | 270/1770 [00:12<01:16, 19.73it/s]

Batches:  15%|█▌        | 272/1770 [00:12<01:16, 19.68it/s]

Batches:  16%|█▌        | 275/1770 [00:12<01:10, 21.10it/s]

Batches:  16%|█▌        | 278/1770 [00:12<01:10, 21.23it/s]

Batches:  16%|█▌        | 281/1770 [00:13<01:06, 22.29it/s]

Batches:  16%|█▌        | 284/1770 [00:13<01:09, 21.40it/s]

Batches:  16%|█▌        | 287/1770 [00:13<01:13, 20.04it/s]

Batches:  16%|█▋        | 290/1770 [00:13<01:16, 19.29it/s]

Batches:  16%|█▋        | 292/1770 [00:13<01:19, 18.66it/s]

Batches:  17%|█▋        | 294/1770 [00:13<01:21, 18.16it/s]

Batches:  17%|█▋        | 296/1770 [00:13<01:22, 17.95it/s]

Batches:  17%|█▋        | 299/1770 [00:14<01:18, 18.77it/s]

Batches:  17%|█▋        | 301/1770 [00:14<01:18, 18.79it/s]

Batches:  17%|█▋        | 304/1770 [00:14<01:15, 19.30it/s]

Batches:  17%|█▋        | 306/1770 [00:14<01:16, 19.13it/s]

Batches:  17%|█▋        | 309/1770 [00:14<01:09, 20.93it/s]

Batches:  18%|█▊        | 312/1770 [00:14<01:11, 20.41it/s]

Batches:  18%|█▊        | 315/1770 [00:14<01:15, 19.26it/s]

Batches:  18%|█▊        | 317/1770 [00:14<01:16, 19.05it/s]

Batches:  18%|█▊        | 319/1770 [00:15<01:19, 18.35it/s]

Batches:  18%|█▊        | 321/1770 [00:15<01:19, 18.26it/s]

Batches:  18%|█▊        | 323/1770 [00:15<01:18, 18.37it/s]

Batches:  18%|█▊        | 325/1770 [00:15<01:19, 18.25it/s]

Batches:  18%|█▊        | 327/1770 [00:15<01:19, 18.25it/s]

Batches:  19%|█▊        | 329/1770 [00:15<01:20, 17.97it/s]

Batches:  19%|█▉        | 332/1770 [00:15<01:16, 18.76it/s]

Batches:  19%|█▉        | 334/1770 [00:15<01:18, 18.34it/s]

Batches:  19%|█▉        | 336/1770 [00:15<01:16, 18.68it/s]

Batches:  19%|█▉        | 339/1770 [00:16<01:12, 19.83it/s]

Batches:  19%|█▉        | 342/1770 [00:16<01:09, 20.61it/s]

Batches:  19%|█▉        | 345/1770 [00:16<01:04, 22.10it/s]

Batches:  20%|█▉        | 348/1770 [00:16<01:00, 23.32it/s]

Batches:  20%|█▉        | 351/1770 [00:16<01:00, 23.63it/s]

Batches:  20%|██        | 354/1770 [00:16<00:58, 24.27it/s]

Batches:  20%|██        | 357/1770 [00:16<00:58, 24.30it/s]

Batches:  20%|██        | 360/1770 [00:16<00:56, 24.88it/s]

Batches:  21%|██        | 363/1770 [00:17<00:56, 24.95it/s]

Batches:  21%|██        | 366/1770 [00:17<00:53, 26.06it/s]

Batches:  21%|██        | 369/1770 [00:17<00:56, 24.87it/s]

Batches:  21%|██        | 372/1770 [00:17<00:56, 24.60it/s]

Batches:  21%|██        | 375/1770 [00:17<00:55, 25.36it/s]

Batches:  21%|██▏       | 378/1770 [00:17<00:52, 26.27it/s]

Batches:  22%|██▏       | 381/1770 [00:17<00:52, 26.28it/s]

Batches:  22%|██▏       | 384/1770 [00:17<00:53, 26.03it/s]

Batches:  22%|██▏       | 387/1770 [00:18<00:52, 26.54it/s]

Batches:  22%|██▏       | 390/1770 [00:18<00:53, 25.90it/s]

Batches:  22%|██▏       | 393/1770 [00:18<00:52, 26.13it/s]

Batches:  22%|██▏       | 396/1770 [00:18<00:52, 26.29it/s]

Batches:  23%|██▎       | 399/1770 [00:18<00:52, 26.34it/s]

Batches:  23%|██▎       | 402/1770 [00:18<00:50, 27.04it/s]

Batches:  23%|██▎       | 405/1770 [00:18<00:52, 25.96it/s]

Batches:  23%|██▎       | 408/1770 [00:18<00:51, 26.49it/s]

Batches:  23%|██▎       | 411/1770 [00:18<00:51, 26.26it/s]

Batches:  23%|██▎       | 414/1770 [00:19<00:52, 25.73it/s]

Batches:  24%|██▎       | 417/1770 [00:19<00:51, 26.33it/s]

Batches:  24%|██▎       | 420/1770 [00:19<00:49, 27.33it/s]

Batches:  24%|██▍       | 423/1770 [00:19<00:48, 27.68it/s]

Batches:  24%|██▍       | 426/1770 [00:19<00:48, 27.63it/s]

Batches:  24%|██▍       | 429/1770 [00:19<00:47, 28.15it/s]

Batches:  24%|██▍       | 432/1770 [00:19<00:47, 27.97it/s]

Batches:  25%|██▍       | 435/1770 [00:19<00:48, 27.42it/s]

Batches:  25%|██▍       | 438/1770 [00:19<00:50, 26.20it/s]

Batches:  25%|██▍       | 441/1770 [00:20<00:50, 26.40it/s]

Batches:  25%|██▌       | 444/1770 [00:20<00:49, 26.53it/s]

Batches:  25%|██▌       | 447/1770 [00:20<00:49, 26.69it/s]

Batches:  25%|██▌       | 450/1770 [00:20<00:50, 26.08it/s]

Batches:  26%|██▌       | 453/1770 [00:20<00:50, 26.00it/s]

Batches:  26%|██▌       | 456/1770 [00:20<00:50, 25.98it/s]

Batches:  26%|██▌       | 459/1770 [00:20<00:51, 25.55it/s]

Batches:  26%|██▌       | 462/1770 [00:20<00:50, 25.94it/s]

Batches:  26%|██▋       | 465/1770 [00:20<00:51, 25.42it/s]

Batches:  26%|██▋       | 468/1770 [00:21<00:50, 25.95it/s]

Batches:  27%|██▋       | 471/1770 [00:21<00:49, 26.45it/s]

Batches:  27%|██▋       | 474/1770 [00:21<00:48, 26.82it/s]

Batches:  27%|██▋       | 477/1770 [00:21<00:47, 27.49it/s]

Batches:  27%|██▋       | 480/1770 [00:21<00:46, 27.53it/s]

Batches:  27%|██▋       | 483/1770 [00:21<00:46, 27.51it/s]

Batches:  27%|██▋       | 486/1770 [00:21<00:46, 27.56it/s]

Batches:  28%|██▊       | 489/1770 [00:21<00:50, 25.44it/s]

Batches:  28%|██▊       | 492/1770 [00:21<00:48, 26.19it/s]

Batches:  28%|██▊       | 495/1770 [00:22<00:48, 26.18it/s]

Batches:  28%|██▊       | 498/1770 [00:22<00:48, 26.18it/s]

Batches:  28%|██▊       | 501/1770 [00:22<00:49, 25.60it/s]

Batches:  28%|██▊       | 504/1770 [00:22<00:49, 25.36it/s]

Batches:  29%|██▊       | 507/1770 [00:22<00:49, 25.72it/s]

Batches:  29%|██▉       | 510/1770 [00:22<00:54, 23.06it/s]

Batches:  29%|██▉       | 513/1770 [00:22<00:54, 22.88it/s]

Batches:  29%|██▉       | 516/1770 [00:22<00:51, 24.34it/s]

Batches:  29%|██▉       | 519/1770 [00:23<00:49, 25.36it/s]

Batches:  29%|██▉       | 522/1770 [00:23<00:47, 26.32it/s]

Batches:  30%|██▉       | 525/1770 [00:23<00:46, 27.06it/s]

Batches:  30%|██▉       | 528/1770 [00:23<00:44, 27.82it/s]

Batches:  30%|███       | 531/1770 [00:23<00:46, 26.38it/s]

Batches:  30%|███       | 534/1770 [00:23<00:46, 26.85it/s]

Batches:  30%|███       | 537/1770 [00:23<00:45, 27.08it/s]

Batches:  31%|███       | 540/1770 [00:23<00:45, 27.10it/s]

Batches:  31%|███       | 543/1770 [00:23<00:44, 27.45it/s]

Batches:  31%|███       | 546/1770 [00:24<00:44, 27.66it/s]

Batches:  31%|███       | 549/1770 [00:24<00:44, 27.58it/s]

Batches:  31%|███       | 552/1770 [00:24<00:45, 26.77it/s]

Batches:  31%|███▏      | 555/1770 [00:24<00:44, 27.07it/s]

Batches:  32%|███▏      | 558/1770 [00:24<00:44, 27.15it/s]

Batches:  32%|███▏      | 561/1770 [00:24<00:46, 25.95it/s]

Batches:  32%|███▏      | 564/1770 [00:24<00:45, 26.73it/s]

Batches:  32%|███▏      | 567/1770 [00:24<00:45, 26.48it/s]

Batches:  32%|███▏      | 570/1770 [00:24<00:45, 26.18it/s]

Batches:  32%|███▏      | 573/1770 [00:25<00:46, 25.91it/s]

Batches:  33%|███▎      | 576/1770 [00:25<00:45, 26.29it/s]

Batches:  33%|███▎      | 579/1770 [00:25<00:45, 26.14it/s]

Batches:  33%|███▎      | 582/1770 [00:25<00:45, 26.25it/s]

Batches:  33%|███▎      | 585/1770 [00:25<00:44, 26.37it/s]

Batches:  33%|███▎      | 588/1770 [00:25<00:43, 27.20it/s]

Batches:  33%|███▎      | 592/1770 [00:25<00:41, 28.47it/s]

Batches:  34%|███▎      | 595/1770 [00:25<00:41, 28.29it/s]

Batches:  34%|███▍      | 598/1770 [00:25<00:43, 26.93it/s]

Batches:  34%|███▍      | 601/1770 [00:26<00:43, 27.10it/s]

Batches:  34%|███▍      | 604/1770 [00:26<00:43, 26.63it/s]

Batches:  34%|███▍      | 607/1770 [00:26<00:45, 25.58it/s]

Batches:  34%|███▍      | 610/1770 [00:26<00:43, 26.64it/s]

Batches:  35%|███▍      | 613/1770 [00:26<00:43, 26.54it/s]

Batches:  35%|███▍      | 616/1770 [00:26<00:42, 26.85it/s]

Batches:  35%|███▍      | 619/1770 [00:26<00:43, 26.16it/s]

Batches:  35%|███▌      | 622/1770 [00:26<00:43, 26.21it/s]

Batches:  35%|███▌      | 625/1770 [00:26<00:42, 26.89it/s]

Batches:  35%|███▌      | 628/1770 [00:27<00:41, 27.30it/s]

Batches:  36%|███▌      | 631/1770 [00:27<00:41, 27.60it/s]

Batches:  36%|███▌      | 634/1770 [00:27<00:41, 27.69it/s]

Batches:  36%|███▌      | 637/1770 [00:27<00:40, 27.92it/s]

Batches:  36%|███▌      | 640/1770 [00:27<00:40, 28.06it/s]

Batches:  36%|███▋      | 643/1770 [00:27<00:39, 28.61it/s]

Batches:  36%|███▋      | 646/1770 [00:27<00:40, 27.68it/s]

Batches:  37%|███▋      | 649/1770 [00:27<00:40, 27.68it/s]

Batches:  37%|███▋      | 652/1770 [00:27<00:40, 27.86it/s]

Batches:  37%|███▋      | 655/1770 [00:28<00:39, 28.47it/s]

Batches:  37%|███▋      | 658/1770 [00:28<00:39, 27.97it/s]

Batches:  37%|███▋      | 662/1770 [00:28<00:38, 29.07it/s]

Batches:  38%|███▊      | 665/1770 [00:28<00:38, 28.44it/s]

Batches:  38%|███▊      | 669/1770 [00:28<00:38, 28.44it/s]

Batches:  38%|███▊      | 672/1770 [00:28<00:38, 28.46it/s]

Batches:  38%|███▊      | 675/1770 [00:28<00:40, 26.91it/s]

Batches:  38%|███▊      | 678/1770 [00:28<00:40, 26.86it/s]

Batches:  38%|███▊      | 681/1770 [00:29<00:39, 27.44it/s]

Batches:  39%|███▊      | 684/1770 [00:29<00:38, 28.04it/s]

Batches:  39%|███▉      | 687/1770 [00:29<00:39, 27.67it/s]

Batches:  39%|███▉      | 690/1770 [00:29<00:38, 27.74it/s]

Batches:  39%|███▉      | 693/1770 [00:29<00:38, 27.69it/s]

Batches:  39%|███▉      | 696/1770 [00:29<00:39, 27.27it/s]

Batches:  39%|███▉      | 699/1770 [00:29<00:39, 27.30it/s]

Batches:  40%|███▉      | 702/1770 [00:29<00:39, 27.25it/s]

Batches:  40%|███▉      | 706/1770 [00:29<00:38, 27.83it/s]

Batches:  40%|████      | 709/1770 [00:30<00:39, 26.69it/s]

Batches:  40%|████      | 712/1770 [00:30<00:39, 27.11it/s]

Batches:  40%|████      | 716/1770 [00:30<00:37, 27.77it/s]

Batches:  41%|████      | 720/1770 [00:30<00:36, 28.93it/s]

Batches:  41%|████      | 724/1770 [00:30<00:35, 29.63it/s]

Batches:  41%|████      | 727/1770 [00:30<00:37, 27.68it/s]

Batches:  41%|████▏     | 731/1770 [00:30<00:36, 28.40it/s]

Batches:  41%|████▏     | 734/1770 [00:30<00:37, 27.50it/s]

Batches:  42%|████▏     | 737/1770 [00:31<00:37, 27.73it/s]

Batches:  42%|████▏     | 740/1770 [00:31<00:36, 28.24it/s]

Batches:  42%|████▏     | 743/1770 [00:31<00:37, 27.13it/s]

Batches:  42%|████▏     | 746/1770 [00:31<00:38, 26.77it/s]

Batches:  42%|████▏     | 749/1770 [00:31<00:37, 27.58it/s]

Batches:  42%|████▏     | 752/1770 [00:31<00:36, 27.73it/s]

Batches:  43%|████▎     | 756/1770 [00:31<00:35, 28.94it/s]

Batches:  43%|████▎     | 760/1770 [00:31<00:33, 29.88it/s]

Batches:  43%|████▎     | 763/1770 [00:31<00:34, 28.88it/s]

Batches:  43%|████▎     | 767/1770 [00:32<00:33, 29.56it/s]

Batches:  44%|████▎     | 770/1770 [00:32<00:34, 29.21it/s]

Batches:  44%|████▎     | 774/1770 [00:32<00:33, 29.60it/s]

Batches:  44%|████▍     | 777/1770 [00:32<00:33, 29.69it/s]

Batches:  44%|████▍     | 780/1770 [00:32<00:34, 28.94it/s]

Batches:  44%|████▍     | 783/1770 [00:32<00:33, 29.08it/s]

Batches:  44%|████▍     | 787/1770 [00:32<00:33, 29.75it/s]

Batches:  45%|████▍     | 790/1770 [00:32<00:34, 28.56it/s]

Batches:  45%|████▍     | 794/1770 [00:32<00:33, 29.44it/s]

Batches:  45%|████▌     | 797/1770 [00:33<00:33, 29.44it/s]

Batches:  45%|████▌     | 800/1770 [00:33<00:33, 28.81it/s]

Batches:  45%|████▌     | 803/1770 [00:33<00:35, 27.59it/s]

Batches:  46%|████▌     | 807/1770 [00:33<00:33, 28.65it/s]

Batches:  46%|████▌     | 810/1770 [00:33<00:34, 27.88it/s]

Batches:  46%|████▌     | 813/1770 [00:33<00:34, 27.80it/s]

Batches:  46%|████▌     | 816/1770 [00:33<00:34, 27.90it/s]

Batches:  46%|████▋     | 820/1770 [00:33<00:33, 28.52it/s]

Batches:  46%|████▋     | 823/1770 [00:34<00:33, 28.18it/s]

Batches:  47%|████▋     | 826/1770 [00:34<00:33, 27.91it/s]

Batches:  47%|████▋     | 829/1770 [00:34<00:33, 27.89it/s]

Batches:  47%|████▋     | 832/1770 [00:34<00:33, 28.26it/s]

Batches:  47%|████▋     | 836/1770 [00:34<00:32, 28.97it/s]

Batches:  47%|████▋     | 839/1770 [00:34<00:34, 26.79it/s]

Batches:  48%|████▊     | 843/1770 [00:34<00:33, 28.02it/s]

Batches:  48%|████▊     | 846/1770 [00:34<00:32, 28.26it/s]

Batches:  48%|████▊     | 850/1770 [00:34<00:31, 29.15it/s]

Batches:  48%|████▊     | 854/1770 [00:35<00:31, 29.43it/s]

Batches:  48%|████▊     | 857/1770 [00:35<00:31, 28.55it/s]

Batches:  49%|████▊     | 860/1770 [00:35<00:32, 27.94it/s]

Batches:  49%|████▉     | 864/1770 [00:35<00:31, 28.95it/s]

Batches:  49%|████▉     | 867/1770 [00:35<00:31, 28.75it/s]

Batches:  49%|████▉     | 870/1770 [00:35<00:31, 28.57it/s]

Batches:  49%|████▉     | 874/1770 [00:35<00:30, 29.34it/s]

Batches:  50%|████▉     | 877/1770 [00:35<00:30, 29.25it/s]

Batches:  50%|████▉     | 881/1770 [00:36<00:29, 30.04it/s]

Batches:  50%|█████     | 885/1770 [00:36<00:29, 30.51it/s]

Batches:  50%|█████     | 889/1770 [00:36<00:28, 30.41it/s]

Batches:  50%|█████     | 893/1770 [00:36<00:29, 29.88it/s]

Batches:  51%|█████     | 896/1770 [00:36<00:30, 29.13it/s]

Batches:  51%|█████     | 899/1770 [00:36<00:30, 28.99it/s]

Batches:  51%|█████     | 902/1770 [00:36<00:30, 28.57it/s]

Batches:  51%|█████     | 905/1770 [00:36<00:30, 28.64it/s]

Batches:  51%|█████▏    | 908/1770 [00:36<00:30, 28.64it/s]

Batches:  51%|█████▏    | 911/1770 [00:37<00:30, 28.25it/s]

Batches:  52%|█████▏    | 914/1770 [00:37<00:30, 28.47it/s]

Batches:  52%|█████▏    | 917/1770 [00:37<00:30, 27.76it/s]

Batches:  52%|█████▏    | 920/1770 [00:37<00:30, 28.12it/s]

Batches:  52%|█████▏    | 924/1770 [00:37<00:28, 29.27it/s]

Batches:  52%|█████▏    | 927/1770 [00:37<00:29, 28.76it/s]

Batches:  53%|█████▎    | 930/1770 [00:37<00:29, 28.45it/s]

Batches:  53%|█████▎    | 933/1770 [00:37<00:29, 28.28it/s]

Batches:  53%|█████▎    | 936/1770 [00:37<00:30, 27.02it/s]

Batches:  53%|█████▎    | 939/1770 [00:38<00:30, 26.92it/s]

Batches:  53%|█████▎    | 942/1770 [00:38<00:30, 27.27it/s]

Batches:  53%|█████▎    | 945/1770 [00:38<00:30, 27.48it/s]

Batches:  54%|█████▎    | 948/1770 [00:38<00:29, 27.85it/s]

Batches:  54%|█████▎    | 951/1770 [00:38<00:30, 26.90it/s]

Batches:  54%|█████▍    | 954/1770 [00:38<00:30, 27.05it/s]

Batches:  54%|█████▍    | 957/1770 [00:38<00:29, 27.81it/s]

Batches:  54%|█████▍    | 960/1770 [00:38<00:29, 27.30it/s]

Batches:  54%|█████▍    | 964/1770 [00:38<00:27, 28.88it/s]

Batches:  55%|█████▍    | 968/1770 [00:39<00:26, 29.85it/s]

Batches:  55%|█████▍    | 972/1770 [00:39<00:26, 29.90it/s]

Batches:  55%|█████▌    | 975/1770 [00:39<00:26, 29.54it/s]

Batches:  55%|█████▌    | 979/1770 [00:39<00:26, 30.16it/s]

Batches:  56%|█████▌    | 983/1770 [00:39<00:26, 30.21it/s]

Batches:  56%|█████▌    | 987/1770 [00:39<00:25, 30.58it/s]

Batches:  56%|█████▌    | 991/1770 [00:39<00:26, 29.05it/s]

Batches:  56%|█████▌    | 995/1770 [00:39<00:25, 29.91it/s]

Batches:  56%|█████▋    | 999/1770 [00:40<00:25, 30.29it/s]

Batches:  57%|█████▋    | 1003/1770 [00:40<00:24, 31.14it/s]

Batches:  57%|█████▋    | 1007/1770 [00:40<00:24, 30.90it/s]

Batches:  57%|█████▋    | 1011/1770 [00:40<00:24, 30.43it/s]

Batches:  57%|█████▋    | 1015/1770 [00:40<00:25, 30.00it/s]

Batches:  58%|█████▊    | 1019/1770 [00:40<00:25, 29.77it/s]

Batches:  58%|█████▊    | 1022/1770 [00:40<00:25, 29.63it/s]

Batches:  58%|█████▊    | 1026/1770 [00:41<00:25, 28.91it/s]

Batches:  58%|█████▊    | 1029/1770 [00:41<00:26, 28.22it/s]

Batches:  58%|█████▊    | 1033/1770 [00:41<00:25, 29.11it/s]

Batches:  59%|█████▊    | 1037/1770 [00:41<00:25, 29.21it/s]

Batches:  59%|█████▉    | 1041/1770 [00:41<00:23, 30.66it/s]

Batches:  59%|█████▉    | 1045/1770 [00:41<00:23, 30.71it/s]

Batches:  59%|█████▉    | 1049/1770 [00:41<00:24, 29.86it/s]

Batches:  59%|█████▉    | 1053/1770 [00:41<00:24, 29.59it/s]

Batches:  60%|█████▉    | 1057/1770 [00:42<00:23, 29.91it/s]

Batches:  60%|█████▉    | 1061/1770 [00:42<00:23, 30.39it/s]

Batches:  60%|██████    | 1065/1770 [00:42<00:23, 30.32it/s]

Batches:  60%|██████    | 1069/1770 [00:42<00:23, 30.40it/s]

Batches:  61%|██████    | 1073/1770 [00:42<00:23, 30.12it/s]

Batches:  61%|██████    | 1077/1770 [00:42<00:23, 30.04it/s]

Batches:  61%|██████    | 1081/1770 [00:42<00:22, 30.09it/s]

Batches:  61%|██████▏   | 1085/1770 [00:42<00:22, 29.81it/s]

Batches:  61%|██████▏   | 1088/1770 [00:43<00:22, 29.75it/s]

Batches:  62%|██████▏   | 1092/1770 [00:43<00:22, 30.17it/s]

Batches:  62%|██████▏   | 1096/1770 [00:43<00:22, 30.32it/s]

Batches:  62%|██████▏   | 1100/1770 [00:43<00:22, 29.71it/s]

Batches:  62%|██████▏   | 1104/1770 [00:43<00:22, 30.12it/s]

Batches:  63%|██████▎   | 1108/1770 [00:43<00:21, 30.27it/s]

Batches:  63%|██████▎   | 1112/1770 [00:43<00:23, 28.57it/s]

Batches:  63%|██████▎   | 1116/1770 [00:44<00:23, 28.00it/s]

Batches:  63%|██████▎   | 1119/1770 [00:44<00:23, 27.94it/s]

Batches:  63%|██████▎   | 1123/1770 [00:44<00:22, 28.95it/s]

Batches:  64%|██████▎   | 1127/1770 [00:44<00:21, 29.45it/s]

Batches:  64%|██████▍   | 1130/1770 [00:44<00:21, 29.55it/s]

Batches:  64%|██████▍   | 1134/1770 [00:44<00:21, 29.57it/s]

Batches:  64%|██████▍   | 1138/1770 [00:44<00:21, 29.84it/s]

Batches:  64%|██████▍   | 1141/1770 [00:44<00:21, 29.01it/s]

Batches:  65%|██████▍   | 1144/1770 [00:45<00:21, 29.18it/s]

Batches:  65%|██████▍   | 1148/1770 [00:45<00:21, 29.44it/s]

Batches:  65%|██████▌   | 1151/1770 [00:45<00:21, 28.57it/s]

Batches:  65%|██████▌   | 1154/1770 [00:45<00:21, 28.12it/s]

Batches:  65%|██████▌   | 1158/1770 [00:45<00:20, 29.22it/s]

Batches:  66%|██████▌   | 1161/1770 [00:45<00:21, 28.38it/s]

Batches:  66%|██████▌   | 1164/1770 [00:45<00:22, 26.67it/s]

Batches:  66%|██████▌   | 1168/1770 [00:45<00:21, 27.86it/s]

Batches:  66%|██████▌   | 1172/1770 [00:45<00:20, 28.65it/s]

Batches:  66%|██████▋   | 1176/1770 [00:46<00:20, 29.57it/s]

Batches:  67%|██████▋   | 1180/1770 [00:46<00:19, 30.42it/s]

Batches:  67%|██████▋   | 1184/1770 [00:46<00:19, 30.23it/s]

Batches:  67%|██████▋   | 1188/1770 [00:46<00:19, 30.58it/s]

Batches:  67%|██████▋   | 1192/1770 [00:46<00:18, 30.43it/s]

Batches:  68%|██████▊   | 1196/1770 [00:46<00:19, 29.46it/s]

Batches:  68%|██████▊   | 1199/1770 [00:46<00:19, 29.44it/s]

Batches:  68%|██████▊   | 1202/1770 [00:47<00:19, 28.82it/s]

Batches:  68%|██████▊   | 1205/1770 [00:47<00:19, 28.98it/s]

Batches:  68%|██████▊   | 1209/1770 [00:47<00:19, 29.41it/s]

Batches:  69%|██████▊   | 1213/1770 [00:47<00:18, 29.72it/s]

Batches:  69%|██████▉   | 1217/1770 [00:47<00:18, 30.55it/s]

Batches:  69%|██████▉   | 1221/1770 [00:47<00:17, 30.74it/s]

Batches:  69%|██████▉   | 1225/1770 [00:47<00:17, 30.52it/s]

Batches:  69%|██████▉   | 1229/1770 [00:47<00:17, 30.06it/s]

Batches:  70%|██████▉   | 1233/1770 [00:48<00:17, 30.09it/s]

Batches:  70%|██████▉   | 1237/1770 [00:48<00:17, 30.30it/s]

Batches:  70%|███████   | 1241/1770 [00:48<00:17, 30.82it/s]

Batches:  70%|███████   | 1245/1770 [00:48<00:16, 31.45it/s]

Batches:  71%|███████   | 1249/1770 [00:48<00:16, 31.19it/s]

Batches:  71%|███████   | 1253/1770 [00:48<00:17, 30.00it/s]

Batches:  71%|███████   | 1257/1770 [00:48<00:17, 29.85it/s]

Batches:  71%|███████   | 1260/1770 [00:48<00:17, 28.77it/s]

Batches:  71%|███████▏  | 1264/1770 [00:49<00:17, 29.24it/s]

Batches:  72%|███████▏  | 1268/1770 [00:49<00:16, 29.62it/s]

Batches:  72%|███████▏  | 1272/1770 [00:49<00:16, 30.10it/s]

Batches:  72%|███████▏  | 1276/1770 [00:49<00:16, 30.36it/s]

Batches:  72%|███████▏  | 1280/1770 [00:49<00:16, 29.75it/s]

Batches:  73%|███████▎  | 1284/1770 [00:49<00:16, 29.82it/s]

Batches:  73%|███████▎  | 1288/1770 [00:49<00:15, 30.88it/s]

Batches:  73%|███████▎  | 1292/1770 [00:49<00:15, 31.54it/s]

Batches:  73%|███████▎  | 1296/1770 [00:50<00:15, 31.48it/s]

Batches:  73%|███████▎  | 1300/1770 [00:50<00:14, 31.55it/s]

Batches:  74%|███████▎  | 1304/1770 [00:50<00:14, 31.13it/s]

Batches:  74%|███████▍  | 1308/1770 [00:50<00:14, 31.51it/s]

Batches:  74%|███████▍  | 1312/1770 [00:50<00:14, 31.75it/s]

Batches:  74%|███████▍  | 1316/1770 [00:50<00:14, 31.00it/s]

Batches:  75%|███████▍  | 1320/1770 [00:50<00:15, 29.44it/s]

Batches:  75%|███████▍  | 1324/1770 [00:51<00:15, 29.48it/s]

Batches:  75%|███████▍  | 1327/1770 [00:51<00:15, 29.36it/s]

Batches:  75%|███████▌  | 1330/1770 [00:51<00:14, 29.41it/s]

Batches:  75%|███████▌  | 1334/1770 [00:51<00:14, 30.26it/s]

Batches:  76%|███████▌  | 1338/1770 [00:51<00:14, 30.54it/s]

Batches:  76%|███████▌  | 1342/1770 [00:51<00:13, 31.10it/s]

Batches:  76%|███████▌  | 1346/1770 [00:51<00:13, 31.68it/s]

Batches:  76%|███████▋  | 1350/1770 [00:51<00:13, 31.32it/s]

Batches:  76%|███████▋  | 1354/1770 [00:51<00:13, 30.51it/s]

Batches:  77%|███████▋  | 1358/1770 [00:52<00:13, 30.78it/s]

Batches:  77%|███████▋  | 1362/1770 [00:52<00:13, 31.30it/s]

Batches:  77%|███████▋  | 1366/1770 [00:52<00:12, 31.60it/s]

Batches:  77%|███████▋  | 1370/1770 [00:52<00:12, 32.40it/s]

Batches:  78%|███████▊  | 1374/1770 [00:52<00:13, 30.40it/s]

Batches:  78%|███████▊  | 1378/1770 [00:52<00:13, 29.48it/s]

Batches:  78%|███████▊  | 1382/1770 [00:52<00:12, 30.58it/s]

Batches:  78%|███████▊  | 1386/1770 [00:53<00:12, 30.98it/s]

Batches:  79%|███████▊  | 1390/1770 [00:53<00:11, 31.76it/s]

Batches:  79%|███████▉  | 1394/1770 [00:53<00:12, 31.08it/s]

Batches:  79%|███████▉  | 1398/1770 [00:53<00:12, 30.63it/s]

Batches:  79%|███████▉  | 1402/1770 [00:53<00:11, 30.86it/s]

Batches:  79%|███████▉  | 1406/1770 [00:53<00:11, 31.60it/s]

Batches:  80%|███████▉  | 1410/1770 [00:53<00:11, 31.63it/s]

Batches:  80%|███████▉  | 1414/1770 [00:53<00:11, 32.11it/s]

Batches:  80%|████████  | 1418/1770 [00:54<00:11, 30.99it/s]

Batches:  80%|████████  | 1422/1770 [00:54<00:10, 31.70it/s]

Batches:  81%|████████  | 1426/1770 [00:54<00:10, 31.94it/s]

Batches:  81%|████████  | 1430/1770 [00:54<00:10, 32.58it/s]

Batches:  81%|████████  | 1434/1770 [00:54<00:10, 31.58it/s]

Batches:  81%|████████  | 1438/1770 [00:54<00:10, 32.28it/s]

Batches:  81%|████████▏ | 1442/1770 [00:54<00:10, 31.37it/s]

Batches:  82%|████████▏ | 1446/1770 [00:54<00:10, 31.09it/s]

Batches:  82%|████████▏ | 1450/1770 [00:55<00:10, 31.33it/s]

Batches:  82%|████████▏ | 1454/1770 [00:55<00:10, 31.57it/s]

Batches:  82%|████████▏ | 1458/1770 [00:55<00:10, 30.42it/s]

Batches:  83%|████████▎ | 1462/1770 [00:55<00:10, 29.98it/s]

Batches:  83%|████████▎ | 1466/1770 [00:55<00:09, 30.67it/s]

Batches:  83%|████████▎ | 1470/1770 [00:55<00:09, 30.71it/s]

Batches:  83%|████████▎ | 1474/1770 [00:55<00:09, 30.48it/s]

Batches:  84%|████████▎ | 1478/1770 [00:55<00:09, 30.42it/s]

Batches:  84%|████████▎ | 1482/1770 [00:56<00:09, 30.36it/s]

Batches:  84%|████████▍ | 1486/1770 [00:56<00:09, 30.16it/s]

Batches:  84%|████████▍ | 1490/1770 [00:56<00:09, 31.09it/s]

Batches:  84%|████████▍ | 1494/1770 [00:56<00:08, 31.31it/s]

Batches:  85%|████████▍ | 1498/1770 [00:56<00:08, 31.74it/s]

Batches:  85%|████████▍ | 1502/1770 [00:56<00:08, 32.32it/s]

Batches:  85%|████████▌ | 1506/1770 [00:56<00:08, 32.64it/s]

Batches:  85%|████████▌ | 1510/1770 [00:56<00:07, 32.58it/s]

Batches:  86%|████████▌ | 1514/1770 [00:57<00:07, 32.51it/s]

Batches:  86%|████████▌ | 1518/1770 [00:57<00:07, 32.94it/s]

Batches:  86%|████████▌ | 1522/1770 [00:57<00:07, 33.13it/s]

Batches:  86%|████████▌ | 1526/1770 [00:57<00:07, 33.16it/s]

Batches:  86%|████████▋ | 1530/1770 [00:57<00:07, 32.57it/s]

Batches:  87%|████████▋ | 1534/1770 [00:57<00:07, 32.56it/s]

Batches:  87%|████████▋ | 1538/1770 [00:57<00:07, 33.12it/s]

Batches:  87%|████████▋ | 1542/1770 [00:57<00:07, 32.47it/s]

Batches:  87%|████████▋ | 1546/1770 [00:58<00:06, 32.55it/s]

Batches:  88%|████████▊ | 1550/1770 [00:58<00:06, 32.97it/s]

Batches:  88%|████████▊ | 1554/1770 [00:58<00:06, 31.77it/s]

Batches:  88%|████████▊ | 1558/1770 [00:58<00:06, 31.68it/s]

Batches:  88%|████████▊ | 1562/1770 [00:58<00:06, 30.99it/s]

Batches:  88%|████████▊ | 1566/1770 [00:58<00:06, 31.67it/s]

Batches:  89%|████████▊ | 1570/1770 [00:58<00:06, 32.03it/s]

Batches:  89%|████████▉ | 1574/1770 [00:58<00:06, 32.64it/s]

Batches:  89%|████████▉ | 1578/1770 [00:59<00:05, 32.32it/s]

Batches:  89%|████████▉ | 1582/1770 [00:59<00:05, 32.83it/s]

Batches:  90%|████████▉ | 1586/1770 [00:59<00:05, 32.26it/s]

Batches:  90%|████████▉ | 1590/1770 [00:59<00:05, 32.39it/s]

Batches:  90%|█████████ | 1594/1770 [00:59<00:05, 32.15it/s]

Batches:  90%|█████████ | 1598/1770 [00:59<00:05, 32.03it/s]

Batches:  91%|█████████ | 1602/1770 [00:59<00:05, 32.79it/s]

Batches:  91%|█████████ | 1606/1770 [00:59<00:05, 32.75it/s]

Batches:  91%|█████████ | 1610/1770 [01:00<00:04, 33.02it/s]

Batches:  91%|█████████ | 1614/1770 [01:00<00:04, 33.39it/s]

Batches:  91%|█████████▏| 1618/1770 [01:00<00:04, 32.91it/s]

Batches:  92%|█████████▏| 1622/1770 [01:00<00:04, 33.14it/s]

Batches:  92%|█████████▏| 1626/1770 [01:00<00:04, 32.54it/s]

Batches:  92%|█████████▏| 1630/1770 [01:00<00:04, 33.35it/s]

Batches:  92%|█████████▏| 1634/1770 [01:00<00:04, 33.34it/s]

Batches:  93%|█████████▎| 1638/1770 [01:00<00:03, 33.92it/s]

Batches:  93%|█████████▎| 1642/1770 [01:00<00:03, 33.89it/s]

Batches:  93%|█████████▎| 1646/1770 [01:01<00:03, 33.76it/s]

Batches:  93%|█████████▎| 1650/1770 [01:01<00:03, 34.38it/s]

Batches:  93%|█████████▎| 1654/1770 [01:01<00:03, 33.68it/s]

Batches:  94%|█████████▎| 1658/1770 [01:01<00:03, 33.30it/s]

Batches:  94%|█████████▍| 1662/1770 [01:01<00:03, 33.52it/s]

Batches:  94%|█████████▍| 1666/1770 [01:01<00:03, 33.57it/s]

Batches:  94%|█████████▍| 1670/1770 [01:01<00:02, 34.73it/s]

Batches:  95%|█████████▍| 1674/1770 [01:01<00:02, 34.97it/s]

Batches:  95%|█████████▍| 1678/1770 [01:02<00:02, 34.71it/s]

Batches:  95%|█████████▌| 1682/1770 [01:02<00:02, 34.96it/s]

Batches:  95%|█████████▌| 1686/1770 [01:02<00:02, 34.26it/s]

Batches:  95%|█████████▌| 1690/1770 [01:02<00:02, 34.98it/s]

Batches:  96%|█████████▌| 1694/1770 [01:02<00:02, 34.47it/s]

Batches:  96%|█████████▌| 1698/1770 [01:02<00:02, 33.60it/s]

Batches:  96%|█████████▌| 1702/1770 [01:02<00:02, 33.48it/s]

Batches:  96%|█████████▋| 1706/1770 [01:02<00:01, 32.61it/s]

Batches:  97%|█████████▋| 1710/1770 [01:03<00:01, 32.40it/s]

Batches:  97%|█████████▋| 1714/1770 [01:03<00:01, 33.41it/s]

Batches:  97%|█████████▋| 1718/1770 [01:03<00:01, 33.99it/s]

Batches:  97%|█████████▋| 1722/1770 [01:03<00:01, 34.19it/s]

Batches:  98%|█████████▊| 1726/1770 [01:03<00:01, 34.91it/s]

Batches:  98%|█████████▊| 1730/1770 [01:03<00:01, 34.74it/s]

Batches:  98%|█████████▊| 1734/1770 [01:03<00:01, 35.34it/s]

Batches:  98%|█████████▊| 1738/1770 [01:03<00:00, 35.81it/s]

Batches:  98%|█████████▊| 1742/1770 [01:03<00:00, 35.12it/s]

Batches:  99%|█████████▊| 1747/1770 [01:04<00:00, 36.88it/s]

Batches:  99%|█████████▉| 1751/1770 [01:04<00:00, 37.30it/s]

Batches:  99%|█████████▉| 1755/1770 [01:04<00:00, 35.63it/s]

Batches:  99%|█████████▉| 1759/1770 [01:04<00:00, 35.71it/s]

Batches: 100%|█████████▉| 1763/1770 [01:04<00:00, 36.51it/s]

Batches: 100%|█████████▉| 1767/1770 [01:04<00:00, 35.71it/s]

Batches: 100%|██████████| 1770/1770 [01:04<00:00, 27.37it/s]

Embeddings ready.

============================================================
Building CRS for tau = 0.3
============================================================

tau = 0.3
Global |V| = 56,635
Global |E| = 186,795
Global density = 0.000116
Global LCC ratio = 0.8208
Backbone w >= 20 |V| = 519
Backbone w >= 20 |E| = 837
Backbone LCC ratio = 1.0000
Backbone modularity = 0.33700226639817166
Time = 0.20 minutes

============================================================
Building CRS for tau = 0.4
============================================================

tau = 0.4
Global |V| = 56,635
Global |E| = 109,022
Global density = 0.000068
Global LCC ratio = 0.6059
Backbone w >= 20 |V| = 408
Backbone w >= 20 |E| = 608
Backbone LCC ratio = 0.9951
Backbone modularity = 0.3560443171946043
Time = 0.19 minutes

============================================================
Building CRS for tau = 0.5
============================================================

tau = 0.5
Global |V| = 56,635
Global |E| = 57,928
Global density = 0.000036
Global LCC ratio = 0.3957
Backbone w >= 20 |V| = 255
Backbone w >= 20 |E| = 344
Backbone LCC ratio = 0.9098
Backbone modularity = 0.34952150800780724
Time = 0.18 minutes

============================================================
Building CRS for tau = 0.6
============================================================

tau = 0.6
Global |V| = 56,635
Global |E| = 28,118
Global density = 0.000018
Global LCC ratio = 0.2249
Backbone w >= 20 |V| = 153
Backbone w >= 20 |E| = 173
Backbone LCC ratio = 0.8693
Backbone modularity = 0.5964805004648758
Time = 0.17 minutes

,tau,nodes_global,edges_global,density_global,components_global,lcc_nodes_global,lcc_edges_global,lcc_ratio_global,nodes_backbone_w20,edges_backbone_w20,density_backbone_w20,components_backbone_w20,lcc_nodes_backbone_w20,lcc_edges_backbone_w20,lcc_ratio_backbone_w20,modularity_backbone_w20,communities_backbone_w20,runtime_seconds
0,0.3,56635,186795,0.000116,8695,46484,185044,0.820765,519,837,0.006227,1,519,837,1.000000,0.337002,6,11.955610
1,0.4,56635,109022,0.000068,19856,34316,106297,0.605915,408,608,0.007323,2,406,607,0.995098,0.356044,7,11.189187
2,0.5,56635,57928,0.000036,31193,22413,54690,0.395745,255,344,0.010622,8,232,328,0.909804,0.349522,10,11.022010
3,0.6,56635,28118,0.000018,40821,12735,24867,0.224861,153,173,0.014878,9,133,160,0.869281,0.596481,12,10.091630

Results saved to:
outputs/tau_sensitivity.csv

,tau,nodes_global,edges_global,density_global,lcc_ratio_global,nodes_backbone_w20,edges_backbone_w20,lcc_ratio_backbone_w20,modularity_backbone_w20,communities_backbone_w20
0,0.3,56635,186795,0.000116,0.820765,519,837,1.000000,0.337002,6
1,0.4,56635,109022,0.000068,0.605915,408,608,0.995098,0.356044,7
2,0.5,56635,57928,0.000036,0.395745,255,344,0.909804,0.349522,10
3,0.6,56635,28118,0.000018,0.224861,153,173,0.869281,0.596481,12

Summary table saved to:
outputs/tau_sensitivity_summary.csv